#!/usr/bin/env python
# -*- coding: utf-8 -*-

import urllib2
import time
import datetime
from bs4 import BeautifulSoup

url = "http://www.dublinbus.ie/en/RTPI/Sources-of-Real-Time-Information/?searchtype=view&searchquery=262"

def baumeister(url):
    req = urllib2.Request(url)
    opened = urllib2.urlopen(req)
    html_doc = opened.read()
    soup = BeautifulSoup(html_doc)
    return soup

soup = baumeister(url)
div = soup.find("div", {"id" : "stop-detail"})
body = soup.find_all("td") #This is where I have tried to fix the problem and failed
print body
result = ""    
for e in body:
    i = e.getText().replace("\t", "").replace("  ", " ").strip().encode(errors="ignore")
    result += i + "\r\n\r\n"
print result 